const color = {
    black: (text: string) => `\x1b[30;1;4m${text}\x1b[0m`,
    red: (text: string) => `\x1b[31;1;4m${text}\x1b[0m`,
    green: (text: string) => `\x1b[32;1;4m${text}\x1b[0m`,
    yellow: (text: string) => `\x1b[33;1;4m${text}\x1b[0m`,
    blue: (text: string) => `\x1b[34;1;4m${text}\x1b[0m`,
    magenta: (text: string) => `\x1b[35;1;4m${text}\x1b[0m`,
    cyan: (text: string) => `\x1b[36;1;4m${text}\x1b[0m`,
    white: (text: string) => `\x1b[37;1;4m${text}\x1b[0m`,
    brightBlack: (text: string) => `\x1b[90;1;4m${text}\x1b[0m`,
    brightRed: (text: string) => `\x1b[91;1;4m${text}\x1b[0m`,
    brightGreen: (text: string) => `\x1b[92;1;4m${text}\x1b[0m`,
    brightYellow: (text: string) => `\x1b[93;1;4m${text}\x1b[0m`,
    brightBlue: (text: string) => `\x1b[94;1;4m${text}\x1b[0m`,
    brightMagenta: (text: string) => `\x1b[95;1;4m${text}\x1b[0m`,
    brightCyan: (text: string) => `\x1b[96;1;4m${text}\x1b[0m`,
    brightWhite: (text: string) => `\x1b[97;1;4m${text}\x1b[0m`,
    bgBlack: (text: string) => `\x1b[40m${text}\x1b[0m`,
    bgRed: (text: string) => `\x1b[41m${text}\x1b[0m`,
    bgGreen: (text: string) => `\x1b[42m${text}\x1b[0m`,
    bgYellow: (text: string) => `\x1b[43m${text}\x1b[0m`,
    bgBlue: (text: string) => `\x1b[44m${text}\x1b[0m`,
    bgMagenta: (text: string) => `\x1b[45m${text}\x1b[0m`,
    bgCyan: (text: string) => `\x1b[46m${text}\x1b[0m`,
    bgWhite: (text: string) => `\x1b[47m${text}\x1b[0m`,
    bgBrightBlack: (text: string) => `\x1b[100m${text}\x1b[0m`,
    bgBrightRed: (text: string) => `\x1b[101m${text}\x1b[0m`,
    bgBrightGreen: (text: string) => `\x1b[102m${text}\x1b[0m`,
    bgBrightYellow: (text: string) => `\x1b[103m${text}\x1b[0m`,
    bgBrightBlue: (text: string) => `\x1b[104m${text}\x1b[0m`,
    bgBrightMagenta: (text: string) => `\x1b[105m${text}\x1b[0m`,
    bgBrightCyan: (text: string) => `\x1b[106m${text}\x1b[0m`,
    bgBrightWhite: (text: string) => `\x1b[107m${text}\x1b[0m`,
  };

export default color;
  